//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.02.15 at 12:56:44 PM CST 
//

package bean;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the edu.uiuc.webservices.rssmanager.bean
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory
{

	private final static QName _QNAME = new QName("", "mycampusbeer");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: edu.uiuc.webservices.rssmanager.bean
	 * 
	 */
	public ObjectFactory()
	{
	}

	public Brand createBrand()
	{
		return new Brand();
	}
	
	public Campus createCampus()
	{
		return new Campus();
	}
	
	public Data createData()
	{
		return new Data();
	}
	
	public Item createItem()
	{
		return new Item();
	}
	
	public Message createMessage()
	{
		return new Message();
	}
	
	public MyCampusEnvironment createMyCampusEnvironment()
	{
		return new MyCampusEnvironment();
	}

	public Product createProduct()
	{
		return new Product();
	}
	
	public Search createSearch()
	{
		return new Search();
	}
	
	public Store createStore()
	{
		return new Store();
	}
	
	public Submitter createSubmitter()
	{
		return new Submitter();
	}
	
	public WorkingStorage createWorkingStorage()
	{
		return new WorkingStorage();
	}
	
	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link RssComplexType }{@code >}}
	 * 
	 */
//	@XmlElementDecl(namespace = "", name = "rss")
//	public JAXBElement<RssComplexType> createRss(RssComplexType value)
//	{
//		return new JAXBElement<RssComplexType>(_Rss_QNAME, RssComplexType.class, null, value);
//	}

}
